# Generated by Django 4.2.7 on 2025-09-25 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(verbose_name='配置值')),
                ('config_type', models.CharField(choices=[('system', '系统配置'), ('ai', 'AI配置'), ('security', '安全配置'), ('notification', '通知配置'), ('other', '其他')], max_length=20, verbose_name='配置类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '应用配置',
                'verbose_name_plural': '应用配置',
                'db_table': 'app_configs',
                'indexes': [models.Index(fields=['key'], name='app_configs_key_20ee88_idx'), models.Index(fields=['config_type'], name='app_configs_config__d47716_idx'), models.Index(fields=['is_active'], name='app_configs_is_acti_665a08_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100, verbose_name='操作动作')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='模型名称')),
                ('object_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='对象ID')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='变更内容')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '系统操作日志',
                'verbose_name_plural': '系统操作日志',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='system_logs_user_id_1b370d_idx'), models.Index(fields=['created_at'], name='system_logs_created_2e006d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('notification_type', models.CharField(choices=[('system', '系统通知'), ('chat', '聊天通知'), ('emotion', '情绪提醒'), ('crisis', '危机预警'), ('emergency', '紧急通知'), ('reminder', '提醒')], max_length=20, verbose_name='通知类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=10, verbose_name='优先级')),
                ('related_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联模型')),
                ('related_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='关联ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_sent', models.BooleanField(default=False, verbose_name='是否已发送')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['priority'], name='notificatio_priorit_17ee5f_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
