# Generated by Django 4.2.7 on 2025-09-27 02:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='加密存储，游客用户使用guest_前缀', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码或游客标识', regex='^(1[3-9]\\d{9}|g[a-f0-9]{8}|1\\d{10})$')], verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='头像')),
                ('age_group', models.CharField(choices=[('teen', '青少年 (12-18岁)'), ('young', '青年 (19-35岁)'), ('middle', '中年 (36-59岁)'), ('elder', '老年 (60岁+)')], default='young', max_length=10, verbose_name='年龄段')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', '其他'), ('prefer_not_say', '不愿透露')], default='prefer_not_say', max_length=20, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('is_guest', models.BooleanField(default=False, verbose_name='游客用户')),
                ('parent_phone', models.CharField(blank=True, help_text='青少年用户必填，加密存储', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码或游客标识', regex='^(1[3-9]\\d{9}|g[a-f0-9]{8}|1\\d{10})$')], verbose_name='家长手机号')),
                ('parental_consent', models.BooleanField(default=False, verbose_name='家长同意')),
                ('parental_mode', models.BooleanField(default=False, verbose_name='家长监督模式')),
                ('helper_phone', models.CharField(blank=True, help_text='老年用户子女手机号，加密存储', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码或游客标识', regex='^(1[3-9]\\d{9}|g[a-f0-9]{8}|1\\d{10})$')], verbose_name='子女联系方式')),
                ('voice_priority', models.BooleanField(default=False, verbose_name='语音优先模式')),
                ('color_theme', models.CharField(default='warmOrange', max_length=20, verbose_name='主题色')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='推送通知')),
                ('data_sync_enabled', models.BooleanField(default=True, verbose_name='数据同步')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后活跃时间')),
                ('is_data_deleted', models.BooleanField(default=False, verbose_name='数据已删除')),
                ('data_deletion_scheduled', models.DateTimeField(blank=True, null=True, verbose_name='数据删除计划时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='所在地')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='职业')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='教育背景')),
                ('mental_health_concerns', models.TextField(blank=True, verbose_name='心理健康关注点')),
                ('therapy_history', models.TextField(blank=True, verbose_name='治疗历史')),
                ('medication_info', models.TextField(blank=True, verbose_name='用药信息')),
                ('preferred_communication_style', models.CharField(choices=[('formal', '正式'), ('casual', '随意'), ('empathetic', '共情'), ('solution_focused', '解决方案导向')], default='empathetic', max_length=20, verbose_name='偏好的沟通风格')),
                ('share_data_for_research', models.BooleanField(default=False, verbose_name='同意数据用于研究')),
                ('anonymous_data_sharing', models.BooleanField(default=True, verbose_name='匿名数据共享')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('verification_code', models.CharField(max_length=6, verbose_name='验证码')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='重置令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
            ],
            options={
                'verbose_name': '密码重置验证码',
                'verbose_name_plural': '密码重置验证码',
                'db_table': 'password_reset_tokens',
                'indexes': [models.Index(fields=['phone', 'is_used'], name='password_re_phone_1ac210_idx'), models.Index(fields=['token'], name='password_re_token_060a1f_idx'), models.Index(fields=['expires_at'], name='password_re_expires_8e96b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='会话密钥')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('device_info', models.JSONField(default=dict, verbose_name='设备信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活动时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户会话',
                'verbose_name_plural': '用户会话',
                'db_table': 'user_sessions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'), models.Index(fields=['session_key'], name='user_sessio_session_cc84b9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['age_group'], name='users_age_gro_92883b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_active'], name='users_last_ac_323696_idx'),
        ),
    ]
