import { ref, computed } from 'vue'

// 语言状态
const currentLanguage = ref(localStorage.getItem('language') || 'zh')

// 翻译文本
const translations = {
  zh: {
    // 通用
    home: '首页',
    chat: '对话',
    profile: '我的',
    emergency: '紧急求助',
    login: '登录',
    register: '注册',
    logout: '退出登录',
    save: '保存',
    cancel: '取消',
    confirm: '确认',
    edit: '编辑',
    delete: '删除',
    add: '添加',
    search: '搜索',
    loading: '加载中...',
    error: '错误',
    success: '成功',
    warning: '警告',
    info: '信息',
    user: '用户',
    welcomeBack: '欢迎回来',
    guestMode: '游客模式',
    goodMorning: '早上好',
    goodNoon: '中午好',
    goodAfternoon: '下午好',
    goodEvening: '晚上好',
    lateNight: '夜深了，注意休息',
    viewAll: '查看全部',
    overallTrend: '整体趋势',
    emotionMonitoring: '情绪监测',
    emotionTrend: '情绪趋势',
    overallStatus: '整体状态',
    lifePlanning: '人生规划',
    teenSpecialSettings: '青少年用户特殊设置',
    elderlyUserSettings: '老年用户辅助设置',
    enterPhoneNumber: '请输入手机号',
    passwordMin6: '请输入密码（至少6位）',
    reEnterPassword: '请再次输入密码',
    loginSuccess: '登录成功！',
    registerSuccess: '注册成功！',
    welcomeToOmnisolace: '欢迎加入Omnisolace',
    loginFailed: '登录失败，请检查手机号和密码',
    registerFailed: '注册失败，请稍后重试',
    passwordMismatch: '两次输入的密码不一致',
    troubleContactCustomerService: '遇到问题？联系客服：',
    serviceStandard: '本服务遵循《心理疏导对话机器人特性规范》GB/T',
    featureComingSoon: '{feature}功能即将上线',
    noConversationHistory: '还没有对话记录，开始您的第一次对话吧',
    noMessages: '暂无消息',
    justNow: '刚刚',
    minutesAgo: '分钟前',
    hoursAgo: '小时前',
    daysAgo: '天前',
    happy: '开心',
    sad: '难过',
    anxious: '焦虑',
    angry: '愤怒',
    neutral: '平静',
    conversationCount: '对话次数',
    continuousDays: '连续使用天数',
    emotionTrendLast7Days: '最近7天情绪趋势',
    modifyContact: '修改联系方式',
    notSet: '未设置',
    
    // 首页
    welcome: '每个年龄的安心，Omnisolace 都懂。',
    subtitle: '全年龄段AI心理疏导机器人',
    quickFeatures: '快速功能',
    recentEmotions: '最近情绪',
    recentChats: '最近对话',
    ageSpecificContent: '年龄段专属内容',
    startChat: '开始对话',
    viewProfile: '查看档案',
    emergencyHelp: '紧急求助',
    
    // 聊天页面
    psychologicalCounseling: '心理疏导',
    aiAssistantServing: 'AI助手正在为您服务',
    newChat: '新建对话',
    chatHistory: '历史对话',
    clearCurrentChat: '清空当前对话',
    enterYourMessage: '输入您想说的话...',
    enterYourMessageElder: '请输入您想说的话，或点击语音按钮说话...',
    enterYourMessageMobile: '请输入...',
    send: '发送',
    voiceInput: '语音输入',
    voiceInputTip: '建议优先使用语音输入，点击下方语音按钮开始说话',
    recognizing: '识别中',
    emotionMonitoring: '情绪监测',
    currentEmotion: '当前情绪',
    emotionTrend: '情绪趋势',
    overallStatus: '整体状态',
    improving: '改善中',
    declining: '需关注',
    stable: '稳定',
    personalizedSuggestions: '个性化建议',
    tryDeepBreathing: '试试深呼吸练习',
    exerciseHelps: '适当运动有助放松',
    getEnoughSleep: '保持充足睡眠',
    mindfulnessMeditation: '焦虑时可以尝试正念冥想',
    
    // 个人中心
    personalCenter: '个人中心',
    userInfo: '用户信息',
    psychologicalProfile: '心理档案',
    viewDetails: '查看详情',
    chatCount: '对话次数',
    continuousDays: '连续使用天数',
    recentEmotionTrend: '最近7天情绪趋势',
    generateReport: '生成心理报告',
    displayMode: '显示模式',
    themeColors: '主题色彩',
    teenMode: '青少年模式',
    youngMode: '青年模式',
    middleMode: '中年模式',
    elderMode: '老年模式',
    teenModeDesc: '明快色彩，家长监督功能',
    youngModeDesc: '简洁高效，职场生活导向',
    middleModeDesc: '稳重实用，家庭事业平衡',
    elderModeDesc: '大字体，语音优先，简化操作',
    teenSettings: '青少年设置',
    parentalMode: '家长监督模式',
    parentalModeDesc: '允许家长查看使用情况摘要',
    parentContact: '家长联系方式',
    modifyContact: '修改联系方式',
    elderSettings: '老年用户设置',
    voicePriority: '语音优先模式',
    voicePriorityDesc: '优先使用语音输入和播放',
    childContact: '子女联系方式',
    generalSettings: '通用设置',
    pushNotifications: '推送通知',
    pushNotificationsDesc: '接收重要提醒和更新',
    dataSync: '数据同步',
    dataSyncDesc: '自动备份对话记录',
    emergencyContacts: '紧急联系人',
    addContact: '添加联系人',
    noEmergencyContacts: '暂无紧急联系人',
    otherActions: '其他操作',
    exportData: '导出我的数据',
    clearChatHistory: '清除对话记录',
    aboutOmnisolace: '关于 Omnisolace',
    otherOperations: '其他操作',
    exportMyData: '导出我的数据',
    clearChatRecords: '清空聊天记录',
    managePersonalInfo: '管理个人信息',
    childrenContact: '子女联系方式',
    voicePriorityEnabled: '语音优先已开启',
    voicePriorityDisabled: '语音优先已关闭',
    notificationsEnabled: '通知已开启',
    notificationsDenied: '通知权限被拒绝',
    notificationsDisabled: '通知已关闭',
    emergencyContactDeleted: '紧急联系人已删除',
    dataExportComingSoon: '数据导出功能即将上线',
    confirmClearChat: '确定要清空所有聊天记录吗？',
    chatRecordsCleared: '聊天记录已清空',
    confirmLogout: '确定要退出登录吗？',
    loggedOut: '已退出登录',
    
    // 清空聊天记录确认
    clearChatWarning: '此操作不可撤销',
    clearChatNotice: '重要提醒',
    clearChatNoticeDesc: '清空聊天记录后，所有对话历史将被永久删除，无法恢复。请谨慎操作。',
    enterPassword: '请输入密码',
    enterPasswordPlaceholder: '请输入您的密码',
    confirmStatement: '确认语句',
    confirmStatementTemplate: '我，{0}，确认清空本账户的聊天记录',
    confirmStatementPlaceholder: '请完整输入上述确认语句',
    passwordRequired: '请输入密码',
    passwordIncorrect: '密码错误',
    statementRequired: '请输入确认语句',
    statementIncorrect: '确认语句不正确',
    clearChatFailed: '清空聊天记录失败，请稍后重试',
    
    // 登录页面
    phoneNumber: '手机号',
    password: '密码',
    confirmPassword: '确认密码',
    selectAgeGroup: '请选择您的年龄段',
    teen: '青少年',
    young: '青年',
    middle: '中年',
    elder: '老年',
    teenRange: '12-18岁',
    youngRange: '19-35岁',
    middleRange: '36-59岁',
    elderRange: '60岁+',
    teenSpecialSettings: '青少年用户特殊设置',
    elderSpecialSettings: '老年用户辅助设置',
    parentPhoneRequired: '家长手机号（必填）',
    parentConsent: '我已获得家长同意使用此服务，并理解家长有权查看我的使用情况摘要',
    helperPhoneOptional: '子女联系方式（选填）',
    helperPhoneDesc: '子女可协助管理账户',
    voicePriorityRecommended: '优先使用语音交互（推荐）',
    agreeTerms: '我已阅读并同意',
    userAgreement: '用户协议',
    privacyPolicy: '隐私政策',
    guestExperience: '游客体验',
    contactSupport: '遇到问题？联系客服：400-161-9995',
    serviceStandard: '本服务遵循《心理疏导对话机器人特性规范》GB/T',
    
    // 主题色
    warmOrange: '暖阳橘',
    warmOrangeDesc: '全龄适配・普适温暖',
    softPinkBrown: '柔粉棕',
    softPinkBrownDesc: '女性友好・细腻治愈',
    amberYellow: '琥珀黄',
    amberYellowDesc: '活力温暖・适配青少年',
    caramelBrown: '焦糖棕',
    caramelBrownDesc: '稳重温暖・适配中年/老年',
    cherryPink: '樱花粉',
    cherryPinkDesc: '轻治愈・适配年轻群体',
    
    // 情绪相关
    happy: '开心',
    sad: '难过',
    anxious: '焦虑',
    angry: '愤怒',
    neutral: '平静',
    
    // 欢迎消息
    teenWelcome: '嗨，年轻的朋友！',
    youngWelcome: '你好，很高兴认识你！',
    middleWelcome: '您好，欢迎来到这里！',
    elderWelcome: '您好，我是您的AI助手！',
    teenWelcomeMsg: '我是你的AI心理助手，可以陪你聊聊学习、生活中的困扰，一起面对成长路上的挑战。',
    youngWelcomeMsg: '我是你的AI心理助手，无论是工作压力、情感问题，还是人生规划，我们都可以一起探讨。',
    middleWelcomeMsg: '我是您的AI心理助手，理解中年生活的不易，愿意倾听您的心声，提供专业的心理支持。',
    elderWelcomeMsg: '我是您的AI心理助手，会耐心倾听您的想法，陪伴您度过每一个需要支持的时刻。',
    youCanTalkAbout: '您可以和我聊聊：',
    
    // Chat.vue 缺失的翻译键
    teenWelcomeTitle: '嗨，年轻的朋友！',
    youngWelcomeTitle: '你好，很高兴认识你！',
    middleWelcomeTitle: '您好，欢迎来到这里！',
    elderWelcomeTitle: '您好，我是您的AI助手！',
    teenWelcomeMessage: '我是你的AI心理助手，可以陪你聊聊学习、生活中的困扰，一起面对成长路上的挑战。',
    youngWelcomeMessage: '我是你的AI心理助手，无论是工作压力、情感问题，还是人生规划，我们都可以一起探讨。',
    middleWelcomeMessage: '我是您的AI心理助手，理解中年生活的不易，愿意倾听您的心声，提供专业的心理支持。',
    elderWelcomeMessage: '我是您的AI心理助手，会耐心倾听您的想法，陪伴您度过每一个需要支持的时刻。',
    youCanChatAbout: '您可以和我聊聊：',
    
    // 快速话题 - 更具体的键名
    parentConflicts: '和父母总是有矛盾',
    lonelyAtSchool: '在学校感到孤单',
    confusedAboutFuture: '对未来感到迷茫',
    relationshipProblems: '感情问题困扰着我',
    careerPlanningConfusion: '不知道如何规划职业',
    alwaysAnxious: '总是感到焦虑不安',
    childEducationWorries: '担心孩子的教育问题',
    careerBottleneckFeeling: '感到职业遇到瓶颈',
    communicationDifficultiesWithChildren: '和子女沟通有困难',
    difficultyAdaptingToRetirement: '适应退休生活有困难',
    healthWorriesElder: '担心身体健康问题',
    
    // 情绪建议
    deepBreathing: '试试深呼吸练习',
    moderateExercise: '适当运动有助放松',
    adequateSleep: '保持充足睡眠',
    
    // 输入提示
    inputPlaceholderElderMobile: '请输入...',
    inputPlaceholderElderDesktop: '请输入您想说的话，或点击语音按钮说话...',
    inputPlaceholderDefault: '输入您想说的话...',
    
    // 语音相关
    voiceInputSuggestion: '建议优先使用语音输入，点击下方语音按钮开始说话',
    listening: '识别中',
    browserNotSupportSpeech: '您的浏览器不支持语音识别',
    microphonePermissionNeeded: '需要麦克风权限才能使用语音输入',
    
    // 对话框相关
    dialogCleared: '对话已清空',
    
    // Chat.vue 硬编码文本的翻译键
    chatHistory: '历史对话',
    searchChatHistory: '搜索聊天记录',
    noSearchResults: '没有找到相关结果',
    noChatHistory: '暂无聊天记录',
    
    // AI回复消息
    teenResponse1: '我理解你现在的感受。青春期确实会遇到很多挑战，但这也是成长的一部分。',
    teenResponse2: '你的想法很正常，很多同龄人都会有类似的困扰。我们一起来看看如何应对吧。',
    teenResponse3: '感谢你愿意和我分享这些。作为青少年，面对这样的问题确实不容易。',
    youngResponse1: '我能感受到你的压力。作为年轻人，在这个阶段确实需要面对很多选择和挑战。',
    youngResponse2: '你提到的这个问题很多人都会遇到。让我们一起分析一下可能的解决方案。',
    youngResponse3: '谢谢你的信任。职场和生活的平衡确实需要时间来摸索。',
    middleResponse1: '我理解您现在的处境。中年阶段承担的责任确实很重，您的感受完全可以理解。',
    middleResponse2: '您提到的问题很有代表性。让我们从实际的角度来看看如何缓解这种压力。',
    middleResponse3: '感谢您的分享。平衡工作和家庭确实需要智慧和耐心。',
    elderResponse1: '我很理解您的感受。这个年龄段确实会面临一些特殊的挑战，但也有很多美好的可能。',
    elderResponse2: '您的经历很宝贵。让我们一起探讨如何让生活更加充实和快乐。',
    elderResponse3: '谢谢您愿意和我交流。您的智慧和经验对我来说也很珍贵。',
    aiErrorResponse: '抱歉，我现在遇到了一些技术问题，请稍后再试。如果您需要紧急帮助，请点击紧急求助按钮。',
    
    // 快速话题
    studyPressure: '我最近学习压力很大',
    parentConflict: '和父母总是有矛盾',
    schoolLonely: '在学校感到孤单',
    futureConfused: '对未来感到迷茫',
    workPressure: '工作压力让我喘不过气',
    relationshipIssues: '感情问题困扰着我',
    careerPlanning: '不知道如何规划职业',
    alwaysAnxious: '总是感到焦虑不安',
    workFamilyBalance: '工作和家庭难以平衡',
    childEducation: '担心孩子的教育问题',
    careerBottleneck: '感到职业遇到瓶颈',
    healthConcerns: '身体健康让我担忧',
    oftenLonely: '经常感到孤独',
    childCommunication: '和子女沟通有困难',
    retirementAdaptation: '适应退休生活有困难',
    healthWorries: '担心身体健康问题',
    
    // Additional Profile translations
    dataSyncEnabled: '数据同步已开启',
    dataSyncDisabled: '数据同步已关闭',
    reportSuccess: '心理报告生成成功',
    reportSentToEmail: '已发送到您的邮箱',
    reportFailed: '报告生成失败，请稍后重试',
    deleteContactConfirm: '确定要删除这个紧急联系人吗？',
    
    // Emergency Modal translations
    emergencyDescription: '如果您正在经历心理危机，请立即寻求专业帮助',
    personalEmergencyContacts: '个人紧急联系人',
    close: '关闭',
    call: '拨打',
    visit: '访问',
    send: '发送',
    psychologicalHelpline: '心理援助热线',
    psychologicalHelplineDesc: '24小时免费心理咨询',
    lifeline: '生命热线',
    lifelineDesc: '自杀危机干预',
    onlinePsychologicalConsulting: '在线心理咨询',
    onlinePsychologicalConsultingDesc: '专业心理咨询师在线服务',
    crisisSMSSupport: '危机短信支持',
    crisisSMSSupportDesc: '发送"帮助"到以下号码',
    emergencyContactOpened: '已为您打开{name}',
    personalContact: '个人联系人',
    
    // About Modal translations
    version: '版本',
    productIntroduction: '产品介绍',
    productDescription: 'Omnisolace 是一款专为全年龄段用户设计的AI心理疏导机器人。我们致力于为青少年、青年、中年和老年用户提供专业、安全、便捷的心理健康服务，帮助用户更好地管理情绪、缓解压力、提升心理健康水平。',
    coreFeatures: '核心特性',
    technicalArchitecture: '技术架构',
    frontendTechnology: '前端技术',
    aiTechnology: 'AI 技术',
    securityAndPrivacy: '安全与隐私',
    dataEncryption: '数据加密：采用AES-256加密算法，确保数据传输和存储安全',
    privacyProtection: '隐私保护：对话记录7天自动脱敏，用户可随时删除个人数据',
    complianceCertification: '合规认证：严格遵循《心理疏导对话机器人特性规范》GB/T',
    contactUs: '联系我们',
    customerService: '客服热线',
    emailSupport: '邮箱支持',
    officialWebsite: '官方网站',
    importantStatement: '重要声明',
    disclaimer: 'Omnisolace 是AI辅助心理疏导工具，不能替代专业心理治疗。如遇严重心理问题或精神疾病，请及时寻求专业医疗机构的帮助。我们的服务仅限于情绪疏导和心理健康维护。',
    copyrightProtected: '本软件受知识产权法保护',
    gotIt: '知道了',
    currentVersionIsLatest: '当前已是最新版本',
    allAgeAdaptation: '全年龄段适配',
    allAgeAdaptationDesc: '针对青少年、青年、中年、老年四个群体提供差异化服务',
    multimodalEmotionRecognition: '多模态情绪识别',
    multimodalEmotionRecognitionDesc: '结合文本、语音、行为三维度分析，准确识别用户情绪状态',
    professionalPsychologicalFramework: '专业心理框架',
    professionalPsychologicalFrameworkDesc: '基于认知行为疗法(CBT)等科学心理干预方法',
    crisisWarningSystem: '危机预警系统',
    crisisWarningSystemDesc: '实时监测高危关键词，10秒内启动紧急干预流程',
    privacySecurityProtection: '隐私安全保护',
    privacySecurityProtectionDesc: '端到端加密，数据自动脱敏，严格保护用户隐私',
    pwaOfflineSupport: 'PWA离线支持',
    pwaOfflineSupportDesc: '支持离线使用，可添加到桌面，提供原生应用体验',
    
    // EditProfile Modal translations
    editPersonalInfo: '编辑个人信息',
    changeAvatar: '更换头像',
    nickname: '昵称',
    enterNickname: '请输入昵称',
    phoneNumber: '手机号',
    
    // PsychProfile Modal translations
    psychProfileDetails: '心理档案详情',
    exportReport: '导出报告',
    totalConversations: '总对话次数',
    avgEmotionScore: '平均情绪分数',
    emotionImprovementRate: '情绪改善率',
    
    // Home page specific translations
    youthNotConfused: '青春不迷茫，心理有支撑',
    studyPressureRelation: '学习压力、人际关系、青春期困惑，我们陪你一起面对',
    workplaceJourney: '职场路上，心理护航',
    workplaceCompetition: '职场竞争、人际关系、职业规划，专业AI为你指点迷津',
    middleAgePressure: '中年压力，智慧化解',
    workFamilyHealth: '工作家庭、健康管理、人生规划，全方位心理支持',
    sunsetBeautiful: '夕阳无限好，心理更健康',
    enjoyLaterLife: '退休生活、健康养生、家庭关系，让晚年更精彩',
    psychologicalHealth: '心理健康，从心开始',
    professionalAI: '专业AI心理疏导，24小时贴心陪伴',
    
    // Quick features
    moodAssessment: '情绪测评',
    interestCommunity: '兴趣社区',
    personalSettings: '个人设置',
    studyStressRelief: '学习减压',
    socialGuidance: '社交指导',
    relationshipConsultation: '情感咨询',
    familyBalance: '家庭平衡',
    memoryTraining: '记忆训练',
    
    // Teen zone
    teenZone: '青少年专区',
    studyStressManagement: '学习压力管理',
    studyMethods: '科学学习方法，轻松应对考试压力',
    adolescentConfusion: '青春期困惑',
    bodyMindDevelopment: '身心发展指导，健康成长每一步',
    parentChildCommunication: '亲子沟通',
    improveParentRelationship: '改善亲子关系，增进家庭和谐',
    interestDevelopment: '兴趣发展',
    discoverSelf: '发现自我潜能，探索人生方向',
    
    // Young zone
    youngZone: '青年专区',
    workplaceAdaptation: '职场适应',
    workplaceAdaptationDesc: '职场新人指导，快速融入工作环境',
    emotionalLife: '情感生活',
    loveMarriage: '恋爱婚姻指导，建立健康情感关系',
    selfGrowth: '自我成长',
    personalValue: '个人价值实现，职业发展规划',
    lifeBalance: '生活平衡',
    workLifeBalance: '工作生活平衡，享受美好人生',
    
    // Middle age zone
    middleAgeZone: '中年专区',
    careerBottleneck: '职业瓶颈',
    middleAgeCareer: '中年职业转型，重新规划人生方向',
    familyResponsibilities: '家庭责任',
    coupleChildrenElderly: '夫妻关系、子女教育、老人赡养',
    physicalMentalHealth: '身心健康管理，预防亚健康状态',
    midlifeCrisis: '中年危机应对，重新定义人生价值',
    
    // Elderly zone
    elderlyZone: '老年专区',
    lonelinessRelief: '孤独缓解',
    socialActivities: '社交活动建议，丰富晚年生活',
    childrenRelationship: '与子女关系改善，增进家庭温暖',
    healthPreservation: '养生保健',
    healthAdaptation: '健康适应指导，科学养生方法',
    lifeAdaptation: '生活适应',
    retirementAdaptationDesc: '退休生活适应，享受悠闲时光',
    
    // Emotions
    happy: '开心',
    neutral: '平静',
    anxious: '焦虑',
    sad: '难过',
    
    // Time formats
    justNow: '刚刚',
    minutesAgo: '分钟前',
    hoursAgo: '小时前',
    daysAgo: '天前',
    noMessages: '暂无消息',
    
    // Trends
    improving: '改善中',
    needsAttention: '需关注',
    stable: '稳定',
    
    // Buttons & Actions
    cancel: '取消',
    send: '发送',
    
    // 反馈相关翻译
    positiveFeedbackTitle: '谢谢你的认可，我们会继续优化进步',
    negativeFeedbackTitle: '谢谢你的反馈，我们会继续优化进步',
    correctness: '正确性',
    normativeness: '规范性',
    regardingAnswer: '针对回答',
    regardingFormat: '针对格式',
    regardingQuestion: '针对问题',
    accurateAndEffective: '准确有效',
    comprehensiveAnswer: '回答全面',
    correctStance: '立场正确',
    standardFormat: '格式规范',
    factualError: '事实错误',
    incompleteContent: '内容不完整',
    calculationError: '计算错误',
    reasoningError: '推理错误',
    unprofessionalContent: '内容不专业',
    illegalHarmful: '违法有害',
    formatError: '格式错误',
    repetitiveContent: '内容重复',
    garbledText: '乱码错误',
    needsDiagram: '需画图但生成文本',
    understandingError: '理解错误',
    contextError: '上下文错误',
    unrecognizedError: '未识别问题中的错误',
    additionalFeedback: '请写下更多反馈内容',
    additionalFeedbackPlaceholder: '请写下更多反馈内容',
    submitting: '提交中',
    submit: '提交',
    feedbackSubmittedSuccessfully: '反馈提交成功，感谢您的建议',
    feedbackSubmissionFailed: '反馈提交失败，请稍后重试',
    copyMessage: '复制消息',
    regenerateMessage: '重新生成',
    likeMessage: '点赞',
    dislikeMessage: '踩',
    editMessage: '编辑消息',
    stopOutput: '停止回答',
    outputStopped: '输出已停止',
    stopOutputFailed: '停止输出失败',
    notEnoughDataForTrend: '暂无足够数据生成趋势图',
    aiThinking: '正在思考...',
    aiResponding: '正在输出...',
    generatingEmotionData: '正在生成情绪分析和个性化建议...',
    
    // 危机预警消息
    crisisWarningKeyword: '⚠️ 我注意到您可能遇到了困难。如果您正在经历危机，请立即寻求专业帮助。',
    crisisActionList: '您可以：',
    crisisHotline1: '拨打心理援助热线：400-161-9995（24小时）',
    crisisHotline2: '拨打生命热线：010-82951332',
    crisisEmergencyButton: '点击右上角的紧急求助按钮获取更多帮助',
    crisisNotAlone: '请记住，您并不孤单，总有人愿意帮助您。',
    
    crisisEmergencyHigh: '🚨 紧急情况！检测到您可能处于危机中。',
    crisisActionImmediate: '请立即：',
    crisisContactEmergency: '联系您的紧急联系人',
    crisisLifePrecious: '您的生命很宝贵，请不要独自承受，立即寻求帮助！',
    
    crisisMediumWarning: '⚠️ 我注意到您的情绪状态需要特别关注。',
    crisisSuggestions: '建议：',
    crisisFeelOverwhelmed: '如果感到难以承受，请拨打心理援助热线：400-161-9995',
    crisisGetProfessional: '点击右上角的紧急求助按钮获取专业支持',
    crisisSeekCounselor: '考虑寻求专业心理咨询师的帮助',
    crisisSeekingHelpBrave: '请记住，寻求帮助是勇敢的表现。',
    
    // 浏览器通知
    notificationEmergencyTitle: '紧急提醒',
    notificationEmergencyBody: '检测到您可能需要紧急帮助，请立即寻求专业支持',
    
    // 危机检测消息
    crisisDetectedByAI: 'AI检测到高度危机（等级{level}）',
    
    // 紧急求助相关
    help: '帮助',
    emergencyEventLogged: '紧急求助事件'
  },
  
  en: {
    // Common
    home: 'Home',
    chat: 'Chat',
    profile: 'Profile',
    emergency: 'Emergency',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    search: 'Search',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    user: 'User',
    welcomeBack: 'Welcome back',
    guestMode: 'Guest Mode',
    goodMorning: 'Good Morning',
    goodNoon: 'Good Noon',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    lateNight: 'Late night, take care and rest',
    viewAll: 'View All',
    overallTrend: 'Overall Trend',
    emotionMonitoring: 'Emotion Monitoring',
    emotionTrend: 'Emotion Trend',
    overallStatus: 'Overall Status',
    lifePlanning: 'Life Planning',
    teenSpecialSettings: 'Teen Special Settings',
    elderlyUserSettings: 'Elderly User Settings',
    enterPhoneNumber: 'Please enter phone number',
    passwordMin6: 'Please enter password (at least 6 digits)',
    reEnterPassword: 'Please re-enter password',
    loginSuccess: 'Login successful!',
    registerSuccess: 'Registration successful!',
    welcomeToOmnisolace: 'Welcome to Omnisolace',
    loginFailed: 'Login failed, please check phone number and password',
    registerFailed: 'Registration failed, please try again later',
    passwordMismatch: 'Passwords do not match',
    troubleContactCustomerService: 'Encountered problems? Contact customer service:',
    serviceStandard: 'This service complies with "Psychological Counseling Chatbot Characteristics Specification" GB/T',
    featureComingSoon: '{feature} feature coming soon',
    noConversationHistory: 'No conversation history yet, start your first conversation!',
    noMessages: 'No messages',
    justNow: 'Just now',
    minutesAgo: ' minutes ago',
    hoursAgo: ' hours ago',
    daysAgo: ' days ago',
    happy: 'Happy',
    sad: 'Sad',
    anxious: 'Anxious',
    angry: 'Angry',
    neutral: 'Neutral',
    conversationCount: 'Conversation Count',
    continuousDays: 'Continuous Days',
    emotionTrendLast7Days: 'Recent 7-Day Emotion Trend',
    modifyContact: 'Modify Contact',
    notSet: 'Not Set',
    
    // Home
    welcome: 'Omnisolace gets your peace of mind—at any age.',
    subtitle: 'AI Psychological Counseling Robot for All Ages',
    quickFeatures: 'Quick Features',
    recentEmotions: 'Recent Emotions',
    recentChats: 'Recent Chats',
    ageSpecificContent: 'Age-Specific Content',
    startChat: 'Start Chat',
    viewProfile: 'View Profile',
    emergencyHelp: 'Emergency Help',
    
    // Chat
    psychologicalCounseling: 'Psychological Counseling',
    aiAssistantServing: 'AI Assistant is serving you',
    newChat: 'New Chat',
    chatHistory: 'Chat History',
    clearCurrentChat: 'Clear Current Chat',
    enterYourMessage: 'Enter your message...',
    enterYourMessageElder: 'Please enter what you want to say, or click the voice button to speak...',
    enterYourMessageMobile: 'Please enter...',
    send: 'Send',
    voiceInput: 'Voice Input',
    voiceInputTip: 'Voice input is recommended, click the voice button below to start speaking',
    recognizing: 'Recognizing',
    emotionMonitoring: 'Emotion Monitoring',
    currentEmotion: 'Current Emotion',
    emotionTrend: 'Emotion Trend',
    overallStatus: 'Overall Status',
    improving: 'Improving',
    declining: 'Needs Attention',
    stable: 'Stable',
    personalizedSuggestions: 'Personalized Suggestions',
    tryDeepBreathing: 'Try deep breathing exercises',
    exerciseHelps: 'Moderate exercise helps relaxation',
    getEnoughSleep: 'Get enough sleep',
    mindfulnessMeditation: 'Try mindfulness meditation when anxious',
    
    // Profile
    personalCenter: 'Personal Center',
    userInfo: 'User Info',
    psychologicalProfile: 'Psychological Profile',
    viewDetails: 'View Details',
    chatCount: 'Chat Count',
    continuousDays: 'Continuous Days',
    recentEmotionTrend: 'Recent 7-day Emotion Trend',
    generateReport: 'Generate Report',
    displayMode: 'Display Mode',
    themeColors: 'Theme Colors',
    teenMode: 'Teen Mode',
    youngMode: 'Young Mode',
    middleMode: 'Middle Mode',
    elderMode: 'Elder Mode',
    teenModeDesc: 'Bright colors, parental supervision',
    youngModeDesc: 'Simple and efficient, career-oriented',
    middleModeDesc: 'Stable and practical, work-family balance',
    elderModeDesc: 'Large fonts, voice priority, simplified operations',
    teenSettings: 'Teen Settings',
    parentalMode: 'Parental Mode',
    parentalModeDesc: 'Allow parents to view usage summary',
    parentContact: 'Parent Contact',
    modifyContact: 'Modify Contact',
    elderSettings: 'Elder Settings',
    voicePriority: 'Voice Priority Mode',
    voicePriorityDesc: 'Prioritize voice input and playback',
    childContact: 'Child Contact',
    generalSettings: 'General Settings',
    pushNotifications: 'Push Notifications',
    pushNotificationsDesc: 'Receive important reminders and updates',
    dataSync: 'Data Sync',
    dataSyncDesc: 'Automatically backup chat records',
    emergencyContacts: 'Emergency Contacts',
    addContact: 'Add Contact',
    noEmergencyContacts: 'No emergency contacts',
    otherActions: 'Other Actions',
    exportData: 'Export My Data',
    clearChatHistory: 'Clear Chat History',
    aboutOmnisolace: 'About Omnisolace',
    otherOperations: 'Other Operations',
    exportMyData: 'Export My Data',
    clearChatRecords: 'Clear Chat Records',
    managePersonalInfo: 'Manage Personal Information',
    childrenContact: 'Children Contact',
    voicePriorityEnabled: 'Voice priority enabled',
    voicePriorityDisabled: 'Voice priority disabled',
    notificationsEnabled: 'Notifications enabled',
    notificationsDenied: 'Notification permission denied',
    notificationsDisabled: 'Notifications disabled',
    emergencyContactDeleted: 'Emergency contact deleted',
    dataExportComingSoon: 'Data export feature coming soon',
    confirmClearChat: 'Are you sure you want to clear all chat records?',
    chatRecordsCleared: 'Chat records cleared',
    confirmLogout: 'Are you sure you want to logout?',
    loggedOut: 'Logged out',
    
    // Clear chat records confirmation
    clearChatWarning: 'This action cannot be undone',
    clearChatNotice: 'Important Notice',
    clearChatNoticeDesc: 'After clearing chat records, all conversation history will be permanently deleted and cannot be recovered. Please proceed with caution.',
    enterPassword: 'Enter Password',
    enterPasswordPlaceholder: 'Please enter your password',
    confirmStatement: 'Confirmation Statement',
    confirmStatementTemplate: 'I, {0}, confirm to clear all chat records of this account',
    confirmStatementPlaceholder: 'Please enter the confirmation statement above',
    passwordRequired: 'Password is required',
    passwordIncorrect: 'Incorrect password',
    statementRequired: 'Confirmation statement is required',
    statementIncorrect: 'Confirmation statement is incorrect',
    clearChatFailed: 'Failed to clear chat records, please try again later',
    
    // Login
    phoneNumber: 'Phone Number',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    selectAgeGroup: 'Please select your age group',
    teen: 'Teen',
    young: 'Young',
    middle: 'Middle',
    elder: 'Elder',
    teenRange: '12-18 years',
    youngRange: '19-35 years',
    middleRange: '36-59 years',
    elderRange: '60+ years',
    teenSpecialSettings: 'Teen Special Settings',
    elderSpecialSettings: 'Elder Special Settings',
    parentPhoneRequired: 'Parent Phone (Required)',
    parentConsent: 'I have obtained parental consent to use this service and understand that parents have the right to view my usage summary',
    helperPhoneOptional: 'Child Contact (Optional)',
    helperPhoneDesc: 'Children can help manage account',
    voicePriorityRecommended: 'Prioritize voice interaction (Recommended)',
    agreeTerms: 'I have read and agree to',
    userAgreement: 'User Agreement',
    privacyPolicy: 'Privacy Policy',
    guestExperience: 'Guest Experience',
    contactSupport: 'Having problems? Contact support: 400-161-9995',
    serviceStandard: 'This service follows the "Psychological Counseling Chatbot Characteristic Specification" GB/T',
    
    // Theme Colors
    warmOrange: 'Warm Orange',
    warmOrangeDesc: 'All-age adaptation・Universal warmth',
    softPinkBrown: 'Soft Pink Brown',
    softPinkBrownDesc: 'Female-friendly・Delicate healing',
    amberYellow: 'Amber Yellow',
    amberYellowDesc: 'Vibrant warmth・Teen-adapted',
    caramelBrown: 'Caramel Brown',
    caramelBrownDesc: 'Stable warmth・Middle/Elder-adapted',
    cherryPink: 'Cherry Pink',
    cherryPinkDesc: 'Light healing・Young-adapted',
    
    // Emotions
    happy: 'Happy',
    sad: 'Sad',
    anxious: 'Anxious',
    angry: 'Angry',
    neutral: 'Neutral',
    
    // Welcome Messages
    teenWelcome: 'Hi, young friend!',
    youngWelcome: 'Hello, nice to meet you!',
    middleWelcome: 'Hello, welcome here!',
    elderWelcome: 'Hello, I am your AI assistant!',
    teenWelcomeMsg: 'I am your AI psychological assistant, I can chat with you about study and life troubles, and face the challenges of growth together.',
    youngWelcomeMsg: 'I am your AI psychological assistant, whether it is work pressure, emotional problems, or life planning, we can discuss together.',
    middleWelcomeMsg: 'I am your AI psychological assistant, understanding the difficulties of middle age, willing to listen to your voice and provide professional psychological support.',
    elderWelcomeMsg: 'I am your AI psychological assistant, I will patiently listen to your thoughts and accompany you through every moment that needs support.',
    youCanTalkAbout: 'You can talk to me about:',
    
    // Chat.vue missing translation keys
    teenWelcomeTitle: 'Hi, young friend!',
    youngWelcomeTitle: 'Hello, nice to meet you!',
    middleWelcomeTitle: 'Hello, welcome here!',
    elderWelcomeTitle: 'Hello, I am your AI assistant!',
    teenWelcomeMessage: 'I am your AI psychological assistant, I can chat with you about study and life troubles, and face the challenges of growth together.',
    youngWelcomeMessage: 'I am your AI psychological assistant, whether it is work pressure, emotional problems, or life planning, we can discuss together.',
    middleWelcomeMessage: 'I am your AI psychological assistant, understanding the difficulties of middle age, willing to listen to your voice and provide professional psychological support.',
    elderWelcomeMessage: 'I am your AI psychological assistant, I will patiently listen to your thoughts and accompany you through every moment that needs support.',
    youCanChatAbout: 'You can talk to me about:',
    
    // Quick topics - more specific keys
    parentConflicts: 'I always have conflicts with my parents',
    lonelyAtSchool: 'I feel lonely at school',
    confusedAboutFuture: 'I feel confused about the future',
    relationshipProblems: 'Relationship issues trouble me',
    careerPlanningConfusion: 'I don\'t know how to plan my career',
    alwaysAnxious: 'I always feel anxious',
    childEducationWorries: 'Worried about children\'s education',
    careerBottleneckFeeling: 'Feel career bottleneck',
    communicationDifficultiesWithChildren: 'Have difficulty communicating with children',
    difficultyAdaptingToRetirement: 'Have difficulty adapting to retirement',
    healthWorriesElder: 'Worried about health problems',
    
    // Emotion suggestions
    deepBreathing: 'Try deep breathing exercises',
    moderateExercise: 'Moderate exercise helps relaxation',
    adequateSleep: 'Get enough sleep',
    
    // Input placeholders
    inputPlaceholderElderMobile: 'Tap here to speak or type',
    inputPlaceholderElderDesktop: 'You can talk to me by typing here, or try using the microphone button to speak.',
    inputPlaceholderDefault: 'What would you like to talk about...',
    
    // Voice related
    voiceInputSuggestion: 'Voice input is recommended, click the voice button below to start speaking',
    listening: 'Recognizing',
    browserNotSupportSpeech: 'Your browser does not support speech recognition',
    microphonePermissionNeeded: 'Microphone permission is needed to use voice input',
    
    // Dialog related
    dialogCleared: 'Dialog cleared',
    
    // Chat.vue hardcoded text translation keys
    chatHistory: 'Chat History',
    searchChatHistory: 'Search chat history',
    noSearchResults: 'No results found',
    noChatHistory: 'No chat history',
    
    // AI response messages
    teenResponse1: 'I understand how you feel. Adolescence does bring many challenges, but it\'s also part of growing up.',
    teenResponse2: 'Your thoughts are normal, and many peers have similar concerns. Let\'s work together to find solutions.',
    teenResponse3: 'Thank you for sharing this with me. As a teenager, facing such issues is indeed not easy.',
    youngResponse1: 'I can feel your pressure. As a young person, this stage does require facing many choices and challenges.',
    youngResponse2: 'The issue you mentioned is common among many people. Let\'s analyze possible solutions together.',
    youngResponse3: 'Thank you for your trust. Balancing work and life does take time to figure out.',
    middleResponse1: 'I understand your situation. Middle age does carry heavy responsibilities, and your feelings are completely understandable.',
    middleResponse2: 'The issue you mentioned is very representative. Let\'s look at how to relieve this pressure from a practical perspective.',
    middleResponse3: 'Thank you for sharing. Balancing work and family indeed requires wisdom and patience.',
    elderResponse1: 'I understand your feelings very well. This age group does face special challenges, but there are also many wonderful possibilities.',
    elderResponse2: 'Your experience is precious. Let\'s explore together how to make life more fulfilling and joyful.',
    elderResponse3: 'Thank you for being willing to communicate with me. Your wisdom and experience are also precious to me.',
    aiErrorResponse: 'Sorry, I\'m experiencing some technical issues right now. Please try again later. If you need emergency help, please click the emergency help button.',
    
    // Quick Topics
    studyPressure: 'I have a lot of study pressure recently',
    parentConflict: 'I always have conflicts with my parents',
    schoolLonely: 'I feel lonely at school',
    futureConfused: 'I feel confused about the future',
    workPressure: 'Work pressure makes me breathless',
    relationshipIssues: 'Relationship issues trouble me',
    careerPlanning: 'I don\'t know how to plan my career',
    alwaysAnxious: 'I always feel anxious',
    workFamilyBalance: 'It\'s hard to balance work and family',
    childEducation: 'Worried about children\'s education',
    careerBottleneck: 'Feel career bottleneck',
    healthConcerns: 'Health concerns worry me',
    oftenLonely: 'Often feel lonely',
    childCommunication: 'Have difficulty communicating with children',
    retirementAdaptation: 'Have difficulty adapting to retirement',
    healthWorries: 'Worried about health problems',
    
    // Additional Profile translations
    dataSyncEnabled: 'Data sync enabled',
    dataSyncDisabled: 'Data sync disabled',
    reportSuccess: 'Psychological report generated successfully',
    reportSentToEmail: 'Sent to your email',
    reportFailed: 'Report generation failed, please try again later',
    deleteContactConfirm: 'Are you sure you want to delete this emergency contact?',
    
    // Emergency Modal translations
    emergencyDescription: 'If you are experiencing a psychological crisis, please seek professional help immediately',
    personalEmergencyContacts: 'Personal Emergency Contacts',
    close: 'Close',
    call: 'Call',
    visit: 'Visit',
    send: 'Send',
    psychologicalHelpline: 'Psychological Helpline',
    psychologicalHelplineDesc: '24-hour free psychological consultation',
    lifeline: 'Lifeline',
    lifelineDesc: 'Suicide crisis intervention',
    onlinePsychologicalConsulting: 'Online Psychological Consulting',
    onlinePsychologicalConsultingDesc: 'Professional psychological counselor online service',
    crisisSMSSupport: 'Crisis SMS Support',
    crisisSMSSupportDesc: 'Send "Help" to the following number',
    emergencyContactOpened: 'Opened {name} for you',
    personalContact: 'Personal Contact',
    
    // About Modal translations
    version: 'Version',
    productIntroduction: 'Product Introduction',
    productDescription: 'Omnisolace is an AI psychological counseling robot designed for users of all ages. We are committed to providing professional, safe, and convenient mental health services for teenagers, young people, middle-aged and elderly users, helping users better manage emotions, relieve stress, and improve mental health.',
    coreFeatures: 'Core Features',
    technicalArchitecture: 'Technical Architecture',
    frontendTechnology: 'Frontend Technology',
    aiTechnology: 'AI Technology',
    securityAndPrivacy: 'Security & Privacy',
    dataEncryption: 'Data Encryption: Uses AES-256 encryption algorithm to ensure data transmission and storage security',
    privacyProtection: 'Privacy Protection: Conversation records are automatically desensitized after 7 days, users can delete personal data at any time',
    complianceCertification: 'Compliance Certification: Strictly follows "Psychological Counseling Chatbot Characteristics Specification" GB/T',
    contactUs: 'Contact Us',
    customerService: 'Customer Service',
    emailSupport: 'Email Support',
    officialWebsite: 'Official Website',
    importantStatement: 'Important Statement',
    disclaimer: 'Omnisolace is an AI-assisted psychological counseling tool and cannot replace professional psychological treatment. If you encounter serious psychological problems or mental illness, please seek help from professional medical institutions in time. Our services are limited to emotional counseling and mental health maintenance.',
    copyrightProtected: 'This software is protected by intellectual property law',
    gotIt: 'Got It',
    currentVersionIsLatest: 'Current version is the latest',
    allAgeAdaptation: 'All-Age Adaptation',
    allAgeAdaptationDesc: 'Provides differentiated services for four groups: teenagers, young people, middle-aged and elderly',
    multimodalEmotionRecognition: 'Multimodal Emotion Recognition',
    multimodalEmotionRecognitionDesc: 'Combines text, voice, and behavior three-dimensional analysis to accurately identify user emotional states',
    professionalPsychologicalFramework: 'Professional Psychological Framework',
    professionalPsychologicalFrameworkDesc: 'Based on scientific psychological intervention methods such as Cognitive Behavioral Therapy (CBT)',
    crisisWarningSystem: 'Crisis Warning System',
    crisisWarningSystemDesc: 'Real-time monitoring of high-risk keywords, emergency intervention process starts within 10 seconds',
    privacySecurityProtection: 'Privacy Security Protection',
    privacySecurityProtectionDesc: 'End-to-end encryption, automatic data desensitization, strictly protecting user privacy',
    pwaOfflineSupport: 'PWA Offline Support',
    pwaOfflineSupportDesc: 'Supports offline use, can be added to desktop, providing native app experience',
    
    // EditProfile Modal translations
    editPersonalInfo: 'Edit Personal Information',
    changeAvatar: 'Change Avatar',
    nickname: 'Nickname',
    enterNickname: 'Please enter nickname',
    phoneNumber: 'Phone Number',
    
    // PsychProfile Modal translations
    psychProfileDetails: 'Psychological Profile Details',
    exportReport: 'Export Report',
    totalConversations: 'Total Conversations',
    avgEmotionScore: 'Average Emotion Score',
    emotionImprovementRate: 'Emotion Improvement Rate',
    
    // Home page specific translations
    youthNotConfused: 'Youth Not Confused, Psychological Support',
    studyPressureRelation: 'Study pressure, relationships, adolescent confusion - we\'re here to help you through it all',
    workplaceJourney: 'Workplace Journey, Psychological Guidance',
    workplaceCompetition: 'Workplace competition, relationships, career planning - professional AI guides your way',
    middleAgePressure: 'Middle Age Pressure, Wisdom Solutions',
    workFamilyHealth: 'Work, family, health management, life planning - comprehensive psychological support',
    sunsetBeautiful: 'Beautiful Sunset, Healthy Mind',
    enjoyLaterLife: 'Retirement life, health preservation, family relationships - make your golden years more wonderful',
    psychologicalHealth: 'Mental Health, Start from the Heart',
    professionalAI: 'Professional AI psychological counseling, 24/7 caring companionship',
    
    // Quick features
    moodAssessment: 'Mood Assessment',
    interestCommunity: 'Interest Community',
    personalSettings: 'Personal Settings',
    studyStressRelief: 'Study Stress Relief',
    socialGuidance: 'Social Guidance',
    relationshipConsultation: 'Relationship Consultation',
    familyBalance: 'Family Balance',
    memoryTraining: 'Memory Training',
    
    // Teen zone
    teenZone: 'Teen Zone',
    studyStressManagement: 'Study Stress Management',
    studyMethods: 'Scientific study methods to easily handle exam pressure',
    adolescentConfusion: 'Adolescent Confusion',
    bodyMindDevelopment: 'Physical and mental development guidance for healthy growth',
    parentChildCommunication: 'Parent-Child Communication',
    improveParentRelationship: 'Improve parent-child relationships and enhance family harmony',
    interestDevelopment: 'Interest Development',
    discoverSelf: 'Discover your potential and explore life direction',
    
    // Young zone
    youngZone: 'Young Adult Zone',
    workplaceAdaptation: 'Workplace Adaptation',
    workplaceAdaptationDesc: 'Guidance for workplace newcomers to quickly integrate into work environment',
    emotionalLife: 'Emotional Life',
    loveMarriage: 'Love and marriage guidance to build healthy emotional relationships',
    selfGrowth: 'Self Growth',
    personalValue: 'Personal value realization and career development planning',
    lifeBalance: 'Life Balance',
    workLifeBalance: 'Work-life balance to enjoy a beautiful life',
    
    // Middle age zone
    middleAgeZone: 'Middle Age Zone',
    careerBottleneck: 'Career Bottleneck',
    middleAgeCareer: 'Middle-age career transition and life direction re-planning',
    familyResponsibilities: 'Family Responsibilities',
    coupleChildrenElderly: 'Couple relationships, children\'s education, elderly care',
    physicalMentalHealth: 'Physical and mental health management to prevent sub-health conditions',
    midlifeCrisis: 'Midlife crisis coping and redefining life values',
    
    // Elderly zone
    elderlyZone: 'Elderly Zone',
    lonelinessRelief: 'Loneliness Relief',
    socialActivities: 'Social activity suggestions to enrich your golden years',
    childrenRelationship: 'Improve relationships with children and enhance family warmth',
    healthPreservation: 'Health Preservation',
    healthAdaptation: 'Health adaptation guidance and scientific health preservation methods',
    lifeAdaptation: 'Life Adaptation',
    retirementAdaptationDesc: 'Retirement life adaptation to enjoy leisurely time',
    
    // Emotions
    happy: 'Happy',
    neutral: 'Neutral',
    anxious: 'Anxious',
    sad: 'Sad',
    
    // Time formats
    justNow: 'Just now',
    minutesAgo: ' minutes ago',
    hoursAgo: ' hours ago',
    daysAgo: ' days ago',
    noMessages: 'No messages',
    
    // Trends
    improving: 'Improving',
    needsAttention: 'Needs Attention',
    stable: 'Stable',
    
    // Buttons & Actions
    cancel: 'Cancel',
    send: 'Send',
    
    // Feedback related translations
    positiveFeedbackTitle: 'Thank you for your recognition, we will continue to improve',
    negativeFeedbackTitle: 'Thank you for your feedback, we will continue to improve',
    correctness: 'Correctness',
    normativeness: 'Normativeness',
    regardingAnswer: 'Regarding Answer',
    regardingFormat: 'Regarding Format',
    regardingQuestion: 'Regarding Question',
    accurateAndEffective: 'Accurate and Effective',
    comprehensiveAnswer: 'Comprehensive Answer',
    correctStance: 'Correct Stance',
    standardFormat: 'Standard Format',
    factualError: 'Factual Error',
    incompleteContent: 'Incomplete Content',
    calculationError: 'Calculation Error',
    reasoningError: 'Reasoning Error',
    unprofessionalContent: 'Unprofessional Content',
    illegalHarmful: 'Illegal/Harmful',
    formatError: 'Format Error',
    repetitiveContent: 'Repetitive Content',
    garbledText: 'Garbled Text',
    needsDiagram: 'Needs Diagram but Generated Text',
    understandingError: 'Understanding Error',
    contextError: 'Context Error',
    unrecognizedError: 'Unrecognized Error in Question',
    additionalFeedback: 'Please write more feedback',
    additionalFeedbackPlaceholder: 'Please write more feedback',
    submitting: 'Submitting',
    submit: 'Submit',
    feedbackSubmittedSuccessfully: 'Feedback submitted successfully, thank you for your suggestions',
    feedbackSubmissionFailed: 'Feedback submission failed, please try again later',
    copyMessage: 'Copy Message',
    regenerateMessage: 'Regenerate',
    likeMessage: 'Like',
    dislikeMessage: 'Dislike',
    editMessage: 'Edit Message',
    stopOutput: 'Stop Answering',
    outputStopped: 'Output Stopped',
    stopOutputFailed: 'Failed to Stop Output',
    notEnoughDataForTrend: 'Not enough data to generate trend chart',
    aiThinking: 'Thinking...',
    aiResponding: 'Responding...',
    generatingEmotionData: 'Generating emotion analysis and personalized suggestions...',
    
    // Crisis warning messages
    crisisWarningKeyword: '⚠️ I notice you may be experiencing difficulties. If you are in crisis, please seek professional help immediately.',
    crisisActionList: 'You can:',
    crisisHotline1: 'Call Mental Health Helpline: 400-161-9995 (24/7)',
    crisisHotline2: 'Call Lifeline: 010-82951332',
    crisisEmergencyButton: 'Click the emergency help button in the top right corner for more assistance',
    crisisNotAlone: 'Please remember, you are not alone, there are always people willing to help you.',
    
    crisisEmergencyHigh: '🚨 Emergency! We detected you may be in crisis.',
    crisisActionImmediate: 'Please immediately:',
    crisisContactEmergency: 'Contact your emergency contacts',
    crisisLifePrecious: 'Your life is precious. Please do not suffer alone, seek help immediately!',
    
    crisisMediumWarning: '⚠️ I notice your emotional state needs special attention.',
    crisisSuggestions: 'Suggestions:',
    crisisFeelOverwhelmed: 'If you feel overwhelmed, please call Mental Health Helpline: 400-161-9995',
    crisisGetProfessional: 'Click the emergency help button in the top right corner for professional support',
    crisisSeekCounselor: 'Consider seeking help from a professional counselor',
    crisisSeekingHelpBrave: 'Please remember, seeking help is a sign of courage.',
    
    // Browser notifications
    notificationEmergencyTitle: 'Emergency Alert',
    notificationEmergencyBody: 'We detected you may need urgent help. Please seek professional support immediately',
    
    // Crisis detection messages
    crisisDetectedByAI: 'AI detected high crisis (level {level})',
    
    // 紧急求助相关
    help: 'Help',
    emergencyEventLogged: 'Emergency Event Logged'
  }
}

// 计算属性
const currentTranslations = computed(() => translations[currentLanguage.value])

// 方法
const setLanguage = (language) => {
  currentLanguage.value = language
  localStorage.setItem('language', language)
  
  // 触发自定义事件，通知其他组件语言已切换
  window.dispatchEvent(new CustomEvent('language-changed', { detail: { language } }))
}

const toggleLanguage = () => {
  const newLanguage = currentLanguage.value === 'zh' ? 'en' : 'zh'
  setLanguage(newLanguage)
}

const t = (key) => {
  return currentTranslations.value[key] || key
}

// 初始化
const initializeLanguage = () => {
  // 应用语言设置
  document.documentElement.lang = currentLanguage.value
}

export {
  currentLanguage,
  currentTranslations,
  setLanguage,
  toggleLanguage,
  t,
  initializeLanguage
}
