# Generated by Django 4.2.7 on 2025-09-26 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('greeting', '问候语'), ('encouragement', '鼓励语'), ('crisis_response', '危机回应'), ('closure', '结束语'), ('age_specific', '年龄段专用')], max_length=20, verbose_name='模板类型')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('age_groups', models.JSONField(default=list, verbose_name='适用年龄段')),
                ('emotion_triggers', models.JSONField(default=list, verbose_name='情绪触发条件')),
                ('keywords', models.JSONField(default=list, verbose_name='关键词')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('effectiveness_score', models.FloatField(default=0.0, verbose_name='效果评分')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '聊天模板',
                'verbose_name_plural': '聊天模板',
                'db_table': 'chat_templates',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='新的对话', max_length=200, verbose_name='会话标题')),
                ('summary', models.TextField(blank=True, verbose_name='会话摘要')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='紧急会话')),
                ('message_count', models.PositiveIntegerField(default=0, verbose_name='消息数量')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='持续时间(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='最后消息时间')),
                ('is_desensitized', models.BooleanField(default=False, verbose_name='已脱敏')),
                ('desensitized_at', models.DateTimeField(blank=True, null=True, verbose_name='脱敏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='消息内容')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('audio', '语音'), ('image', '图片'), ('system_notice', '系统通知')], default='text', max_length=20, verbose_name='消息类型')),
                ('sender_type', models.CharField(choices=[('user', '用户'), ('ai', 'AI助手'), ('system', '系统')], max_length=10, verbose_name='发送者类型')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chat/audio/%Y/%m/', verbose_name='语音文件')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='chat/images/%Y/%m/', verbose_name='图片文件')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('emotion_data', models.JSONField(blank=True, null=True, verbose_name='情绪数据')),
                ('crisis_detected', models.BooleanField(default=False, verbose_name='检测到危机')),
                ('crisis_keywords', models.JSONField(default=list, verbose_name='危机关键词')),
                ('ai_model', models.CharField(blank=True, max_length=50, verbose_name='AI模型')),
                ('ai_confidence', models.FloatField(blank=True, null=True, verbose_name='AI置信度')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('original_content', models.TextField(blank=True, null=True, verbose_name='原始内容')),
                ('is_desensitized', models.BooleanField(default=False, verbose_name='已脱敏')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('helpful', '有帮助'), ('not_helpful', '没帮助'), ('inappropriate', '不当回复'), ('technical_issue', '技术问题')], max_length=20, verbose_name='反馈类型')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], null=True, verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '聊天反馈',
                'verbose_name_plural': '聊天反馈',
                'db_table': 'chat_feedbacks',
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_active'], name='chat_sessio_user_id_d84cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['created_at'], name='chat_sessio_created_d061d1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['is_emergency'], name='chat_sessio_is_emer_3e2bec_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_messag_session_597c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender_type'], name='chat_messag_sender__1cc140_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['crisis_detected'], name='chat_messag_crisis__bcddb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatfeedback',
            unique_together={('user', 'message')},
        ),
    ]
