# Generated by Django 4.2.7 on 2025-10-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatfeedback',
            name='comment',
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='additional_feedback',
            field=models.TextField(blank=True, verbose_name='额外反馈'),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='negative_category',
            field=models.CharField(blank=True, choices=[('factualError', '事实错误'), ('incompleteContent', '内容不完整'), ('calculationError', '计算错误'), ('reasoningError', '推理错误'), ('unprofessionalContent', '内容不专业'), ('illegalHarmful', '违法有害'), ('formatError', '格式错误'), ('repetitiveContent', '内容重复'), ('garbledText', '乱码错误'), ('needsDiagram', '需画图但生成文本')], max_length=25, null=True, verbose_name='负反馈分类'),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='positive_category',
            field=models.CharField(blank=True, choices=[('accurate', '准确有效'), ('comprehensive', '回答全面'), ('correctStance', '立场正确'), ('standardFormat', '格式规范')], max_length=20, null=True, verbose_name='正反馈分类'),
        ),
        migrations.AlterField(
            model_name='chatfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('positive', '正反馈'), ('negative', '负反馈')], max_length=20, verbose_name='反馈类型'),
        ),
        migrations.AddIndex(
            model_name='chatfeedback',
            index=models.Index(fields=['feedback_type'], name='chat_feedba_feedbac_5e5f94_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfeedback',
            index=models.Index(fields=['created_at'], name='chat_feedba_created_09c6ca_idx'),
        ),
    ]
